wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.6
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713532001.0
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.7
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
